### ISSUE TITLE
Implementing loss distribution approach for operational risk

### ISSUE THREAD

**Issue by kwoongbae** [kwoongbae/risk-management-papers#13]
- https://onlinelibrary.wiley.com/doi/epdf/10.1002/asmb.812
- Shevchenko, P. V. (2010).

**Comment by kwoongbae** [comment]
### 1. OpRisk under Basel2
- Referred to as Basel 2, banks are required to hold adequate capital against OpRisk losses
- Estimation of the annual loss distribution by modeling frequency and severity of losses is a well-known actuarial technique.
- This paper considered the Bayesian inference approach that allows to account for expert judgment and parameter uncertainty which are important issues in the OpRisk management.

**Comment by kwoongbae** [comment]
### 4. Modeling severity tail
- One of the popular distributions to model severity is Lognormal (a heavy-tailed distribution, sub-exponential dist where the tail decays slower than any exponential tail)
- Lognormal was suggested for OpRisk at the beginning of Basel 2 development.
- accurate modeling of extremely high losses (the tail of severity distribution) is critical and other heavy-tailed distributions are often considered to be more appropriate

**Comment by kwoongbae** [comment]
### 5. Calculating compound distribution
- Most popular numerical methods are Monte Carlo, Panjer recursion, and fast Fourier transform (FFT) methods.

**Comment by keywoongbae** [comment]
> ### 1. OpRisk under Basel2
> * Referred to as Basel 2, banks are required to hold adequate capital against OpRisk losses
> * Estimation of the annual loss distribution by modeling frequency and severity of losses is a well-known actuarial technique.
> * This paper considered the Bayesian inference approach that allows to account for expert judgment and parameter uncertainty which are important issues in the OpRisk management.

**Comment by kwoongbae** [comment]
### 6. Model fitting
- 저빈도 고심도 케이스에 대해서 빈/심도 추정은 매우 어려움 (very limited data for some risks)
- 추정할 때는 (i) 모수의 최적값 추정, (ii) 모수 불확실성 정량화, (iii) 모델 성능 평가 등이 있는데, 이런 것들은 frequentist 방법과 Bayesian 방법이 있음.

**6.1 Frequentist approach**
- 가장 전통적인 방법론
